const socketEmit = {
  CONNECTION: 'connection',
  DISCONNECT: 'disconnect',
  JOIN: 'join',
  FILE_UPLOAD: 'file',
  FILE_MESSAGE: 'file notify',
  CHAT_MESSAGE: 'chat message',
  RECEIVED: 'received',
  TYPING: 'typing',
  NOTIFY_TYPING: 'notifyTyping',
  NOTIFY_TYPING_GLOBAL: 'notifyTypingGlobal',
  STOP_TYPING: 'stopTyping',
  NOTIFY_STOP_TYPING: 'notifyStopTyping',
  NOTIFY_STOP_TYPING_GLOBAL: 'notifyStopTypingGlobal',
  ALL_ONLINE_NOTIFY_GLOBAL: 'allOnlineNotifyGlobal',
  NOTIFY_ONLINE_USER: 'notifyOnlineUser',
  NOTIFY_UNREAD_GLOBAL: 'notifyUnreadGlobal',
  REFRESH_GLOBAL_GROUP_MEMBER: 'refreshGlobal',
  REFRESH_CHAT_HISTORY_GLOBAL: 'refreshchathistoryglobal',
  NEW_CHAT_CONNECT: 'newChatconnect',
  NEW_GROUP_CREATE: 'newGroupcreate',
  UPDATE_DEAL_NAME: 'updateDealName',
};
export default socketEmit;
