const url = {
  GET_OLD_CHAT: 'chat/list',
  LOAD_CHANNEL_LIST: 'group/list',
  DOWNLOAD_FILE: 'downloadwebfile',
  USER_LIST: 'users/list',
  USER_ALL: 'user/all',
  VENDOR_ALL: 'vendor/all',
  GROUP_MEMBERS_ADD: 'group/members/add',
  GROUP_DETAILS: 'group/details',
  VENDOR_LIST: 'api/get_vender_list',
  GROUP_MEMBER_REMOVE: 'group/members/remove',
  COMPANY_DETAILS: 'api/get_end_user_companies',
  END_USER_LIST: 'api/get_enduser_list',
  CREATE_NEW_DEAL: 'api/create_deal',
  QUOTE_DETAILS: 'api/get_deal_details',
  GENERATE_PO: 'api/generate_po',
  USER_INFO: 'api/get_user_info',
  ALL_COUNTRY: 'api/search_country',
  RATING: 'api/submit_rating',
  PAYMENT_TERM: 'api/get_ship_invoice_address',
  GET_QUOTE_DETAILS: 'api/get_quote_details',
  PIN_GROUP: 'group/pin/add',
  UN_PIN_GROUP: 'group/pin/remove',
};
export default url;
